created ta welcome page that contains two parts, the first part conta…
GSG-FC03/fruit-salad-team-6 pull request #6
Opened 2021-06-24 19:01 UTC by safamohanna95

- [ ] Created HTML Structure:
      

- Create the basic content of the HTML page
 

- [ ] Create the general layout

- divide the page into two parts: upper part and lower part. 
- The upper part contains a fruit basket photo and its shadow
- The lower part contains a header, a paragraph, and a button 

- [ ] Use a flex layout 
- [ ] Styling the HTML elements
- [ ] link the button to the home page

relate #5

2021-06-24 19:04 UTC, MohammedHasan-99 approved these changes, later dismissed

2021-06-24 19:05 UTC, Rawanzaqout submitted a review, later dismissed

2021-06-25 09:54 UTC, sara219 requested changes
Use prettier to format the code (HTML & CSS files)
also, add comments to guide the reviewers.

2021-06-25 09:54 UTC, sara219 commented on index.html
> +    <link rel="stylesheet" href="stylesheets/style.cssgi">
there's an error in the style link, you write _(.cssgi)_, fix it!

![Screenshot from 2021-06-25 12-46-15](https://user-images.githubusercontent.com/47992412/123406298-6e38a380-d5b3-11eb-9b3f-473f3996fd69.png)

2021-06-25 09:54 UTC, sara219 commented on stylesheets/style.css
> +    margin: 0%;
`margin: 0` without `%`

2021-06-25 09:54 UTC, sara219 commented on stylesheets/style.css
> +    justify-content: center;
useless property, delete it

2021-06-25 16:20 UTC, MohammedHasan-99 approved these changes

2021-06-25 16:22 UTC, Rawanzaqout approved these changes

2021-06-26 07:36 UTC, sara219 approved these changes

2021-06-26 15:02 UTC, merged