create home screen layout and dsign
GSG-FC03/fruit-salad-team-6 pull request #8
Opened 2021-06-25 16:13 UTC by MohammedHasan-99

relates #7

- [ ]  create a home screen which consists of:

- upper menu button
- search bar with filter  icon
- the main header
- combo blocks that includes combo photo, name,  price, like icon and add to cart icon.
- combo types menu bar.
- another dish viewer relates to the chosen menu.

- [ ]  make a proper layout for the HTML structure.
- [ ]  style the  HTML elements with CSS:
- white background colour 
- dark blue main header
- the price, like and add icon in orange colour.
- active menu in dark blue
- non-active menu in light blue

2021-06-25 16:20 UTC, safamohanna95 approved these changes, later dismissed

2021-06-25 22:03 UTC, Rawanzaqout submitted a review, later dismissed

2021-06-26 07:48 UTC, sara219 requested changes

2021-06-26 07:48 UTC, sara219 commented on html/home_screen.html
> +            </sectio>
typo in the tag name, `section` instead of `sectio`

2021-06-26 07:48 UTC, sara219 commented on html/home_screen.html
> +            </sectio>
and typo there!

2021-06-26 08:14 UTC, sara219 approved these changes

2021-06-26 09:39 UTC, Rawanzaqout approved these changes

2021-06-26 09:51 UTC, Rawanzaqout approved these changes

2021-06-26 11:48 UTC, merged